# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zorroprotos/plugin/plugin_env.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#zorroprotos/plugin/plugin_env.proto\x12\x05zorro\"F\n\tPluginEnv\x12\x0e\n\x06\x61ppend\x18\x01 \x03(\t\x12\x0f\n\x07prepend\x18\x02 \x03(\t\x12\x10\n\x03set\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x06\n\x04_setB2Z0github.com/Acedyn/zorro-proto/zorroprotos/pluginb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zorroprotos.plugin.plugin_env_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z0github.com/Acedyn/zorro-proto/zorroprotos/plugin'
  _globals['_PLUGINENV']._serialized_start=46
  _globals['_PLUGINENV']._serialized_end=116
# @@protoc_insertion_point(module_scope)
