# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zorroprotos/processor/processor_status.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,zorroprotos/processor/processor_status.proto\x12\x05zorro*o\n\x0fProcessorStatus\x12\x0c\n\x08STARTING\x10\x00\x12\x08\n\x04IDLE\x10\x01\x12\x0e\n\nPROCESSING\x10\x02\x12\x11\n\rSHUTTING_DOWN\x10\x03\x12\r\n\tSHUT_DOWN\x10\x04\x12\x12\n\x0eNOT_RESPONDING\x10\x05\x42\x35Z3github.com/Acedyn/zorro-proto/zorroprotos/processorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zorroprotos.processor.processor_status_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z3github.com/Acedyn/zorro-proto/zorroprotos/processor'
  _globals['_PROCESSORSTATUS']._serialized_start=55
  _globals['_PROCESSORSTATUS']._serialized_end=166
# @@protoc_insertion_point(module_scope)
