// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: internal/context/plugin.proto

package context

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Clients are responsible for executing commands
type Client struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the executable
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Used to differentiate two same clients with a different version
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// User friently version of the name without all its contraints
	Label *string `protobuf:"bytes,3,opt,name=label,proto3,oneof" json:"label,omitempty"`
	// Paths where we should look for the executable
	Paths []string `protobuf:"bytes,4,rep,name=paths,proto3" json:"paths,omitempty"`
	// Defines if this client can be used as a substitute for other clients
	Subsets []string `protobuf:"bytes,5,rep,name=subsets,proto3" json:"subsets,omitempty"`
	// Template to run the program without the client running
	RunProgramTemplate string `protobuf:"bytes,6,opt,name=run_program_template,json=runProgramTemplate,proto3" json:"run_program_template,omitempty"`
	// Template to run the program with the client running
	RunClientTemplate string `protobuf:"bytes,7,opt,name=run_client_template,json=runClientTemplate,proto3" json:"run_client_template,omitempty"`
}

func (x *Client) Reset() {
	*x = Client{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_context_plugin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_internal_context_plugin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_internal_context_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *Client) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Client) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Client) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

func (x *Client) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *Client) GetSubsets() []string {
	if x != nil {
		return x.Subsets
	}
	return nil
}

func (x *Client) GetRunProgramTemplate() string {
	if x != nil {
		return x.RunProgramTemplate
	}
	return ""
}

func (x *Client) GetRunClientTemplate() string {
	if x != nil {
		return x.RunClientTemplate
	}
	return ""
}

// Modifications for a environment variabme by a plugins
type PluginEnv struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Paths to append to the existing paths for path environment variable
	Append []string `protobuf:"bytes,1,rep,name=append,proto3" json:"append,omitempty"`
	// Paths to prepend to the existing paths for path environment variable
	Prepend []string `protobuf:"bytes,2,rep,name=prepend,proto3" json:"prepend,omitempty"`
	// For regular environment variable, the value to set
	Set *string `protobuf:"bytes,3,opt,name=set,proto3,oneof" json:"set,omitempty"`
}

func (x *PluginEnv) Reset() {
	*x = PluginEnv{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_context_plugin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginEnv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginEnv) ProtoMessage() {}

func (x *PluginEnv) ProtoReflect() protoreflect.Message {
	mi := &file_internal_context_plugin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginEnv.ProtoReflect.Descriptor instead.
func (*PluginEnv) Descriptor() ([]byte, []int) {
	return file_internal_context_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginEnv) GetAppend() []string {
	if x != nil {
		return x.Append
	}
	return nil
}

func (x *PluginEnv) GetPrepend() []string {
	if x != nil {
		return x.Prepend
	}
	return nil
}

func (x *PluginEnv) GetSet() string {
	if x != nil && x.Set != nil {
		return *x.Set
	}
	return ""
}

// Where to look for tool declarations
type PluginTools struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commands []string `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	Actions  []string `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	Hooks    []string `protobuf:"bytes,3,rep,name=hooks,proto3" json:"hooks,omitempty"`
	Widgets  []string `protobuf:"bytes,4,rep,name=widgets,proto3" json:"widgets,omitempty"`
}

func (x *PluginTools) Reset() {
	*x = PluginTools{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_context_plugin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginTools) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginTools) ProtoMessage() {}

func (x *PluginTools) ProtoReflect() protoreflect.Message {
	mi := &file_internal_context_plugin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginTools.ProtoReflect.Descriptor instead.
func (*PluginTools) Descriptor() ([]byte, []int) {
	return file_internal_context_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *PluginTools) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *PluginTools) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *PluginTools) GetHooks() []string {
	if x != nil {
		return x.Hooks
	}
	return nil
}

func (x *PluginTools) GetWidgets() []string {
	if x != nil {
		return x.Widgets
	}
	return nil
}

// Plugins register a set of tools, environment variables and clients.
// A set of tools will define what interactions are available or not.
type Plugin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name should be unique and be as simple as possible
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The version is composed of multiple subversions separated with a dot
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// User friently version of the name without all its contraints
	Label *string `protobuf:"bytes,3,opt,name=label,proto3,oneof" json:"label,omitempty"`
	// The path to the plugin definition
	Path *string `protobuf:"bytes,4,opt,name=path,proto3,oneof" json:"path,omitempty"`
	// A list of plugin request that needs to be resolved for this plugin
	Require []string `protobuf:"bytes,5,rep,name=require,proto3" json:"require,omitempty"`
	// Each plugins will alter the environment generated
	Env map[string]*PluginEnv `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Each plugins will alter the environment generated
	Tools *PluginTools `protobuf:"bytes,7,opt,name=tools,proto3,oneof" json:"tools,omitempty"`
	// List of clients to register as available clients to launch
	Clients []*Client `protobuf:"bytes,8,rep,name=clients,proto3" json:"clients,omitempty"`
}

func (x *Plugin) Reset() {
	*x = Plugin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_context_plugin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Plugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plugin) ProtoMessage() {}

func (x *Plugin) ProtoReflect() protoreflect.Message {
	mi := &file_internal_context_plugin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plugin.ProtoReflect.Descriptor instead.
func (*Plugin) Descriptor() ([]byte, []int) {
	return file_internal_context_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *Plugin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plugin) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Plugin) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

func (x *Plugin) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *Plugin) GetRequire() []string {
	if x != nil {
		return x.Require
	}
	return nil
}

func (x *Plugin) GetEnv() map[string]*PluginEnv {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Plugin) GetTools() *PluginTools {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *Plugin) GetClients() []*Client {
	if x != nil {
		return x.Clients
	}
	return nil
}

var File_internal_context_plugin_proto protoreflect.FileDescriptor

var file_internal_context_plugin_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x7a, 0x6f, 0x72, 0x72, 0x6f, 0x22, 0xed, 0x01, 0x0a, 0x06, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x19, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61,
	0x74, 0x68, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x73, 0x65, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x73, 0x65, 0x74, 0x73, 0x12, 0x30, 0x0a, 0x14, 0x72, 0x75,
	0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x72, 0x75, 0x6e, 0x50, 0x72, 0x6f,
	0x67, 0x72, 0x61, 0x6d, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x2e, 0x0a, 0x13,
	0x72, 0x75, 0x6e, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x72, 0x75, 0x6e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x42, 0x08, 0x0a, 0x06,
	0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x5c, 0x0a, 0x09, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x45, 0x6e, 0x76, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x72, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72,
	0x65, 0x70, 0x65, 0x6e, 0x64, 0x12, 0x15, 0x0a, 0x03, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x73, 0x65, 0x74, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04,
	0x5f, 0x73, 0x65, 0x74, 0x22, 0x73, 0x0a, 0x0b, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x54, 0x6f,
	0x6f, 0x6c, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x6f, 0x6f,
	0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x68, 0x6f, 0x6f, 0x6b, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x07, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x73, 0x22, 0xed, 0x02, 0x0a, 0x06, 0x50, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x88, 0x01, 0x01, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x12, 0x28, 0x0a, 0x03, 0x65, 0x6e, 0x76, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x7a, 0x6f, 0x72, 0x72, 0x6f, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x45, 0x6e, 0x76,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03, 0x65, 0x6e, 0x76, 0x12, 0x2d, 0x0a, 0x05, 0x74, 0x6f,
	0x6f, 0x6c, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x7a, 0x6f, 0x72, 0x72,
	0x6f, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x54, 0x6f, 0x6f, 0x6c, 0x73, 0x48, 0x02, 0x52,
	0x05, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x88, 0x01, 0x01, 0x12, 0x27, 0x0a, 0x07, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x7a, 0x6f, 0x72,
	0x72, 0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x73, 0x1a, 0x48, 0x0a, 0x08, 0x45, 0x6e, 0x76, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x26, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x7a, 0x6f, 0x72, 0x72, 0x6f, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x45, 0x6e,
	0x76, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x08, 0x0a, 0x06,
	0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x42,
	0x08, 0x0a, 0x06, 0x5f, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x63, 0x65, 0x64, 0x79, 0x6e, 0x2f, 0x7a,
	0x6f, 0x72, 0x72, 0x6f, 0x2d, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_internal_context_plugin_proto_rawDescOnce sync.Once
	file_internal_context_plugin_proto_rawDescData = file_internal_context_plugin_proto_rawDesc
)

func file_internal_context_plugin_proto_rawDescGZIP() []byte {
	file_internal_context_plugin_proto_rawDescOnce.Do(func() {
		file_internal_context_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_context_plugin_proto_rawDescData)
	})
	return file_internal_context_plugin_proto_rawDescData
}

var file_internal_context_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_context_plugin_proto_goTypes = []interface{}{
	(*Client)(nil),      // 0: zorro.Client
	(*PluginEnv)(nil),   // 1: zorro.PluginEnv
	(*PluginTools)(nil), // 2: zorro.PluginTools
	(*Plugin)(nil),      // 3: zorro.Plugin
	nil,                 // 4: zorro.Plugin.EnvEntry
}
var file_internal_context_plugin_proto_depIdxs = []int32{
	4, // 0: zorro.Plugin.env:type_name -> zorro.Plugin.EnvEntry
	2, // 1: zorro.Plugin.tools:type_name -> zorro.PluginTools
	0, // 2: zorro.Plugin.clients:type_name -> zorro.Client
	1, // 3: zorro.Plugin.EnvEntry.value:type_name -> zorro.PluginEnv
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_context_plugin_proto_init() }
func file_internal_context_plugin_proto_init() {
	if File_internal_context_plugin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_context_plugin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Client); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_context_plugin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginEnv); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_context_plugin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginTools); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_context_plugin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Plugin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_context_plugin_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_internal_context_plugin_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_internal_context_plugin_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_context_plugin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_context_plugin_proto_goTypes,
		DependencyIndexes: file_internal_context_plugin_proto_depIdxs,
		MessageInfos:      file_internal_context_plugin_proto_msgTypes,
	}.Build()
	File_internal_context_plugin_proto = out.File
	file_internal_context_plugin_proto_rawDesc = nil
	file_internal_context_plugin_proto_goTypes = nil
	file_internal_context_plugin_proto_depIdxs = nil
}
