# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zorro_core/network/protos/scheduler_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from zorro_core.network.protos import command_pb2 as zorro__core_dot_network_dot_protos_dot_command__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1zorro_core/network/protos/scheduler_service.proto\x12\x05zorro\x1a\x1bgoogle/protobuf/empty.proto\x1a\'zorro_core/network/protos/command.proto2\xf1\x01\n\x0bZorroClient\x12H\n\x15GetNewCommandRequests\x12\x16.google.protobuf.Empty\x1a\x15.zorro.CommandRequest0\x01\x12L\n\x19GetRunningCommandRequests\x12\x16.google.protobuf.Empty\x1a\x15.zorro.CommandRequest0\x01\x12J\n\x18GetAndSendCommandUpdates\x12\x14.zorro.CommandUpdate\x1a\x14.zorro.CommandUpdate(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zorro_core.network.protos.scheduler_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ZORROCLIENT']._serialized_start=131
  _globals['_ZORROCLIENT']._serialized_end=372
# @@protoc_insertion_point(module_scope)
