# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zorro_core/network/protos/socket.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&zorro_core/network/protos/socket.proto\x12\x05zorro\"\x82\x01\n\x06Socket\x12\x14\n\nraw_string\x18\x01 \x01(\tH\x00\x12\x15\n\x0braw_integer\x18\x02 \x01(\x05H\x00\x12\x14\n\nraw_number\x18\x03 \x01(\x02H\x00\x12\x14\n\nraw_binary\x18\x04 \x01(\x0cH\x00\x12\x0c\n\x04\x63\x61st\x18\x05 \x01(\t\x12\n\n\x02id\x18\x06 \x01(\tB\x05\n\x03rawb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zorro_core.network.protos.socket_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SOCKET']._serialized_start=50
  _globals['_SOCKET']._serialized_end=180
# @@protoc_insertion_point(module_scope)
