# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from zorroprotos.processor import processor_pb2 as zorroprotos_dot_processor_dot_processor__pb2
from zorroprotos.scheduling import scheduler_pb2 as zorroprotos_dot_scheduling_dot_scheduler__pb2


class SchedulingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterProcessor = channel.unary_unary(
                '/zorro.Scheduling/RegisterProcessor',
                request_serializer=zorroprotos_dot_scheduling_dot_scheduler__pb2.ProcessorRegistration.SerializeToString,
                response_deserializer=zorroprotos_dot_processor_dot_processor__pb2.Processor.FromString,
                )


class SchedulingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterProcessor(self, request, context):
        """For processors to start running their commands
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterProcessor': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterProcessor,
                    request_deserializer=zorroprotos_dot_scheduling_dot_scheduler__pb2.ProcessorRegistration.FromString,
                    response_serializer=zorroprotos_dot_processor_dot_processor__pb2.Processor.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zorro.Scheduling', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Scheduling(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterProcessor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zorro.Scheduling/RegisterProcessor',
            zorroprotos_dot_scheduling_dot_scheduler__pb2.ProcessorRegistration.SerializeToString,
            zorroprotos_dot_processor_dot_processor__pb2.Processor.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
