# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zorroprotos/config/plugin_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&zorroprotos/config/plugin_config.proto\x12\x05zorro\"6\n\x0cPluginConfig\x12\x17\n\x0f\x64\x65\x66\x61ult_require\x18\x01 \x03(\t\x12\r\n\x05repos\x18\x02 \x03(\tB2Z0github.com/Acedyn/zorro-proto/zorroprotos/configb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zorroprotos.config.plugin_config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z0github.com/Acedyn/zorro-proto/zorroprotos/config'
  _globals['_PLUGINCONFIG']._serialized_start=49
  _globals['_PLUGINCONFIG']._serialized_end=103
# @@protoc_insertion_point(module_scope)
