# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zorroprotos/config/user_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$zorroprotos/config/user_config.proto\x12\x05zorro\"/\n\nUserConfig\x12!\n\x08language\x18\x01 \x01(\x0e\x32\x0f.zorro.Language*;\n\x08Language\x12\x0b\n\x07\x45nglish\x10\x00\x12\n\n\x06\x46rench\x10\x01\x12\x0b\n\x07Spanish\x10\x02\x12\t\n\x05\x44utch\x10\x03\x42\x32Z0github.com/Acedyn/zorro-proto/zorroprotos/configb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zorroprotos.config.user_config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z0github.com/Acedyn/zorro-proto/zorroprotos/config'
  _globals['_LANGUAGE']._serialized_start=96
  _globals['_LANGUAGE']._serialized_end=155
  _globals['_USERCONFIG']._serialized_start=47
  _globals['_USERCONFIG']._serialized_end=94
# @@protoc_insertion_point(module_scope)
