# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zorro_python/commands/log/log.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from zorroprotos.tools import command_pb2 as zorroprotos_dot_tools_dot_command__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#zorro_python/commands/log/log.proto\x12\x0czorro_python\x1a\x1fzorroprotos/tools/command.proto\"C\n\x08LogInput\x12\x0f\n\x07message\x18\x01 \x01(\t\x12&\n\x05level\x18\x02 \x01(\x0e\x32\x17.zorro_python.LogLevels\"V\n\tLogOutput\x12%\n\rzorro_command\x18\x01 \x01(\x0b\x32\x0e.zorro.Command\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x04*F\n\tLogLevels\x12\t\n\x05\x44\x45\x42UG\x10\x00\x12\x08\n\x04INFO\x10\x01\x12\x0b\n\x07WARNING\x10\x02\x12\t\n\x05\x45RROR\x10\x03\x12\x0c\n\x08\x43RITICAL\x10\x04\x32~\n\x03Log\x12<\n\x07\x45xecute\x12\x16.zorro_python.LogInput\x1a\x17.zorro_python.LogOutput0\x01\x12\x39\n\x04Undo\x12\x16.zorro_python.LogInput\x1a\x17.zorro_python.LogOutput0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zorro_python.commands.log.log_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_LOGLEVELS']._serialized_start=243
  _globals['_LOGLEVELS']._serialized_end=313
  _globals['_LOGINPUT']._serialized_start=86
  _globals['_LOGINPUT']._serialized_end=153
  _globals['_LOGOUTPUT']._serialized_start=155
  _globals['_LOGOUTPUT']._serialized_end=241
  _globals['_LOG']._serialized_start=315
  _globals['_LOG']._serialized_end=441
# @@protoc_insertion_point(module_scope)
