# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zorro_python/commands/concat_str/concat_str.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1zorro_python/commands/concat_str/concat_str.proto\x12\x0czorro_python\"2\n\x0e\x43oncatStrInput\x12\x0f\n\x07stringA\x18\x01 \x01(\t\x12\x0f\n\x07stringB\x18\x02 \x01(\t\"!\n\x0f\x43oncatStrOutput\x12\x0e\n\x06string\x18\x01 \x01(\t2\x9c\x01\n\tConcatStr\x12H\n\x07\x45xecute\x12\x1c.zorro_python.ConcatStrInput\x1a\x1d.zorro_python.ConcatStrOutput0\x01\x12\x45\n\x04Undo\x12\x1c.zorro_python.ConcatStrInput\x1a\x1d.zorro_python.ConcatStrOutput0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zorro_python.commands.concat_str.concat_str_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONCATSTRINPUT']._serialized_start=67
  _globals['_CONCATSTRINPUT']._serialized_end=117
  _globals['_CONCATSTROUTPUT']._serialized_start=119
  _globals['_CONCATSTROUTPUT']._serialized_end=152
  _globals['_CONCATSTR']._serialized_start=155
  _globals['_CONCATSTR']._serialized_end=311
# @@protoc_insertion_point(module_scope)
