# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from zorro_python.commands.concat_str import concat_str_pb2 as zorro__python_dot_commands_dot_concat__str_dot_concat__str__pb2


class ConcatStrStub(object):
    """Simple log message
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_stream(
                '/zorro_python.ConcatStr/Execute',
                request_serializer=zorro__python_dot_commands_dot_concat__str_dot_concat__str__pb2.ConcatStrInput.SerializeToString,
                response_deserializer=zorro__python_dot_commands_dot_concat__str_dot_concat__str__pb2.ConcatStrOutput.FromString,
                )
        self.Undo = channel.unary_stream(
                '/zorro_python.ConcatStr/Undo',
                request_serializer=zorro__python_dot_commands_dot_concat__str_dot_concat__str__pb2.ConcatStrInput.SerializeToString,
                response_deserializer=zorro__python_dot_commands_dot_concat__str_dot_concat__str__pb2.ConcatStrOutput.FromString,
                )


class ConcatStrServicer(object):
    """Simple log message
    """

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Undo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConcatStrServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_stream_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=zorro__python_dot_commands_dot_concat__str_dot_concat__str__pb2.ConcatStrInput.FromString,
                    response_serializer=zorro__python_dot_commands_dot_concat__str_dot_concat__str__pb2.ConcatStrOutput.SerializeToString,
            ),
            'Undo': grpc.unary_stream_rpc_method_handler(
                    servicer.Undo,
                    request_deserializer=zorro__python_dot_commands_dot_concat__str_dot_concat__str__pb2.ConcatStrInput.FromString,
                    response_serializer=zorro__python_dot_commands_dot_concat__str_dot_concat__str__pb2.ConcatStrOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zorro_python.ConcatStr', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ConcatStr(object):
    """Simple log message
    """

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/zorro_python.ConcatStr/Execute',
            zorro__python_dot_commands_dot_concat__str_dot_concat__str__pb2.ConcatStrInput.SerializeToString,
            zorro__python_dot_commands_dot_concat__str_dot_concat__str__pb2.ConcatStrOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Undo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/zorro_python.ConcatStr/Undo',
            zorro__python_dot_commands_dot_concat__str_dot_concat__str__pb2.ConcatStrInput.SerializeToString,
            zorro__python_dot_commands_dot_concat__str_dot_concat__str__pb2.ConcatStrOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
